CREATE DATABASE DB_ThucHanh_TaoKhoaChinh
GO;
USE DB_ThucHanh_TaoKhoaChinh
GO;

--CACH 1
CREATE TABLE Users(
	UserId		INT			IDENTITY(1,1)		PRIMARY KEY,
	UserName	VARCHAR(20)	NOT NULL,
	[Password]	VARCHAR(20)	NOT NULL,
	Email		VARCHAR(30)
)

--CACH 2
CREATE TABLE Students(
	StudentID	INT			IDENTITY(1,1)		NOT NULL,
	FirstName	NVARCHAR(30)	NOT NULL,
	LastName	NVARCHAR(30)	NOT NULL,
	[Address]	NVARCHAR(40)	NOT NULL,
	PRIMARY KEY (StudentID)
)

--ADD PRIMARY KEY ON MULTIPLE COLUMNS

CREATE TABLE Teachers(
	TeacherID	INT			IDENTITY(1,1)		NOT NULL,
	FullName	NVARCHAR(40)	NOT NULL,
	[Address]	NVARCHAR(40)	NOT NULL,
	Email		VARCHAR(30),
	PRIMARY KEY (TeacherID, FullName)
);

--ADD PRIMARY KEY AFTER CREATE TABLE

CREATE TABLE Products(
	ProductName	NVARCHAR(30)	NOT NULL,
	Price		INT				NOT NULL,
	Producer	NVARCHAR(30)	NOT NULL
)

--CREATE NEW COLUMN WITH PRIMARTY KEY

ALTER TABLE Products
	ADD ProductId	INT		IDENTITY(1,1)	PRIMARY KEY;

--ADD PRIMARY KEY TO COLUMN ALREADY

ALTER TABLE Products
	ADD PRIMARY KEY (ProducName);