CREATE DATABASE THUCTAP
GO
USE THUCTAP

CREATE TABLE KHOA(
	MAKHOA			VARCHAR(10)				NOT NULL	PRIMARY KEY,
	TENKHOA			VARCHAR(30)				NOT NULL,
	DIENTHOAI		VARCHAR(10)
)

CREATE TABLE GIANGVIEN(
	MAGV			INT						NOT NULL	PRIMARY KEY,
	HOTENGV			VARCHAR(30)				NOT NULL,
	LUONG			DECIMAL(5,2)			NOT NULL,
	MAKHOA			VARCHAR(10)				FOREIGN KEY REFERENCES KHOA(MAKHOA)
)

CREATE TABLE SINHVIEN(
	MASV			INT						NOT NULL	PRIMARY KEY,
	HOTENSV			VARCHAR(30)				NOT NULL,
	MAKHOA			VARCHAR(10)				FOREIGN KEY REFERENCES KHOA(MAKHOA),
	NAMSINH			INT						NOT NULL,
	QUENQUAN		VARCHAR(30)				NOT NULL
)

CREATE TABLE DETAI(
	MADT			VARCHAR(10)				NOT NULL	PRIMARY KEY,
	TENDT			VARCHAR(30)				NOT NULL,
	KINHPHI			INT,
	NOITHUCTAP		VARCHAR(30)
)

CREATE TABLE HUONGDAN(
	MASV			INT						FOREIGN KEY REFERENCES SINHVIEN(MASV),
	MADT			VARCHAR(10)				FOREIGN KEY REFERENCES DETAI(MADT),
	MAGV			INT						FOREIGN KEY REFERENCES GIANGVIEN(MAGV),
	KETQUA			DECIMAL(5,2)
	PRIMARY KEY (MASV, MADT)
)
