--BASIC
--CAU 1
SELECT MAGV, HOTENGV, TENKHOA
FROM GIANGVIEN
INNER JOIN KHOA
ON GIANGVIEN.MAKHOA = KHOA.MAKHOA

--CAU 2
SELECT MAGV, HOTENGV, TENKHOA
FROM GIANGVIEN
INNER JOIN KHOA
ON GIANGVIEN.MAKHOA = KHOA.MAKHOA
WHERE TENKHOA = 'DIA LY va QLTN'

--CAU 3
SELECT KHOA.TENKHOA, COUNT(SINHVIEN.MASV) AS SOLUONGSV
FROM SINHVIEN
INNER JOIN KHOA
ON SINHVIEN.MAKHOA = KHOA.MAKHOA
GROUP BY TENKHOA,SINHVIEN.MASV

--CAU 4
SELECT SINHVIEN.MASV,SINHVIEN.HOTENSV,SINHVIEN.NAMSINH,KHOA.TENKHOA
FROM SINHVIEN
INNER JOIN KHOA
ON SINHVIEN.MAKHOA = KHOA.MAKHOA
WHERE KHOA.TENKHOA = 'TOAN'

--CAU 5
SELECT KHOA.TENKHOA, COUNT(GIANGVIEN.MAGV) AS SOLUONGGV
FROM GIANGVIEN
INNER JOIN KHOA
ON GIANGVIEN.MAKHOA = KHOA.MAKHOA
WHERE KHOA.TENKHOA = 'CONG NGHE SINH HOC'
GROUP BY KHOA.TENKHOA, GIANGVIEN.MAGV

--CAU 6
SELECT SINHVIEN.HOTENSV, KETQUA
FROM SINHVIEN
INNER JOIN HUONGDAN
ON SINHVIEN.MASV = HUONGDAN.MASV
WHERE KETQUA IS NULL

--CAU 7
SELECT KHOA.TENKHOA, COUNT(GIANGVIEN.MAGV) AS SOLUONGGV
FROM KHOA
INNER JOIN GIANGVIEN
ON KHOA.MAKHOA = GIANGVIEN.MAKHOA
GROUP BY KHOA.TENKHOA,GIANGVIEN.MAGV

--CAU 8
SELECT SINHVIEN.HOTENSV,KHOA.DIENTHOAI
FROM KHOA
INNER JOIN SINHVIEN
ON KHOA.MAKHOA = SINHVIEN.MAKHOA
WHERE SINHVIEN.HOTENSV = 'Le van son'

--ADVANCED
--CAU 1
SELECT *
FROM DETAI
INNER JOIN HUONGDAN
ON DETAI.MADT = HUONGDAN.MADT
INNER JOIN GIANGVIEN
ON HUONGDAN.MAGV = GIANGVIEN.MAGV

--CAU 2
SELECT TENDT, NOITHUCTAP
FROM DETAI
WHERE NOITHUCTAP IS NULL

--CAU 3
SELECT GV.MAGV, GV.HOTENGV, K.TENKHOA, COUNT(HD.MASV) AS SOLUONGSV
FROM GIANGVIEN GV
INNER JOIN HUONGDAN HD
ON GV.MAGV = HD.MAGV
INNER JOIN KHOA K
ON GV.MAKHOA = K.MAKHOA
GROUP BY GV.MAGV, GV.HOTENGV, K.TENKHOA, HD.MASV
HAVING COUNT(HD.MASV)>3

--CAU 4
SELECT TOP 1 MADT, TENDT, KINHPHI
FROM DETAI
ORDER BY KINHPHI DESC

--CAU 5
SELECT DT.MADT, DT.TENDT, COUNT(HD.MASV) AS SOLUONGSV
FROM DETAI DT
INNER JOIN HUONGDAN HD
ON  DT.MADT = HD.MADT
GROUP BY DT.MADT, DT.TENDT, HD.MASV
HAVING COUNT(HD.MASV)>2

--CAU 6
SELECT SV.MASV, SV.HOTENSV, K.TENKHOA, HD.KETQUA
FROM SINHVIEN SV
INNER JOIN KHOA K
ON SV.MAKHOA = K.MAKHOA
INNER JOIN HUONGDAN HD
ON SV.MASV = HD.MASV
WHERE K.TENKHOA = 'DIALY và QLTN'

--CAU 7
SELECT K.TENKHOA, COUNT(SV.MASV) AS SOLUONGSV
FROM KHOA K
INNER JOIN SINHVIEN SV
ON K.MAKHOA = SV.MAKHOA
GROUP BY K.TENKHOA, SV.MASV

--CAU 8
SELECT SV.HOTENSV,SV.QUENQUAN,DT.NOITHUCTAP
FROM HUONGDAN HD
INNER JOIN DETAI DT
ON DT.MADT = HD.MADT
INNER JOIN SINHVIEN SV
ON SV.MASV = HD.MASV
WHERE SV.QUENQUAN = DT.NOITHUCTAP

--CAU 9
SELECT SV.*, HD.KETQUA
FROM SINHVIEN SV
INNER JOIN HUONGDAN HD
ON HD.MASV = SV.MASV
WHERE HD.KETQUA IS NULL

--CAU 10
SELECT SV.MASV, SV.HOTENSV, HD.KETQUA
FROM SINHVIEN SV
INNER JOIN HUONGDAN HD
ON SV.MASV = HD.MASV
WHERE HD.KETQUA = 0


