CREATE DATABASE db_functionSQL
GO;

USE db_functionSQL
GO;

CREATE TABLE INFORMATION(
	ID		INT				NOT NULL	IDENTITY(1,1)	PRIMARY KEY,
	TEN		NVARCHAR(20)	NOT NULL,
	TUOI	INT				NOT NULL,
	KHOAHOC	VARCHAR(5)		NOT NULL,
	SOTIEN	INT				NOT NULL
)

INSERT INTO INFORMATION(TEN, TUOI, KHOAHOC, SOTIEN)
VALUES 
	(N'Hoang', 21, 'CNTT', 400000),
	(N'Viet',19,'DTVT',320000),
	(N'Thanh',18,'KTDN',400000),
	(N'Nhan',19,'CK',450000),
	(N'Huong',20,'TCNH',500000),
	(N'Huong',20,'TCNH',200000)

-- Cau 1
SELECT *
FROM INFORMATION
WHERE TEN = 'Huong'

-- Cau 2
SELECT TEN, SUM(SOTIEN) TONGTIEN
FROM INFORMATION
WHERE TEN = 'Huong'
GROUP BY TEN

-- Cau 3
SELECT TEN
FROM INFORMATION
GROUP BY TEN